// import { Role } from '../roles';
// import { AccessibleNodeDescriptor } from './descriptor';
// import { SliderDescriptor } from './slider';

// // export const simpleRole: Readonly<{
// //   [key in keyof typeof Role]: AccessibleNodeDescriptor;
// // }> = {
// //   none: {
// //     allowedChildren: Object.keys(Role),
// //     allowedAttributes: [...sharedRequiredAttributes],
// //     events: [],
// //     requiredAttributes: [...sharedAllowedAttributes],
// //     tag: 'div',
// //   },
// // };

// export const RoleMapping: Readonly<{
//   [key in keyof typeof Role]: AccessibleNodeDescriptor;
// }> = {
//   none: {
//     allowedChildren: Object.keys(Role),
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: ['id', 'role'],
//     tag: 'div',
//   },
//   alert: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: ['id', 'role'],
//     tag: 'div',
//   },
//   alertdialog: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: ['id', 'role'],
//     tag: 'div',
//   },
//   button: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'button',
//   },
//   checkbox: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'input',
//   },
//   dialog: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'div',
//   },
//   gridcell: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'td',
//   },
//   link: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'a',
//   },
//   log: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'div',
//   },
//   marquee: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'div',
//   },
//   menuitem: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'li',
//   },
//   menuitemcheckbox: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'li',
//   },
//   menuitemradio: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'li',
//   },
//   multilinetextbox: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'textarea',
//   },
//   singleselectoption: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'li',
//   },
//   multiselectoption: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'option',
//   },
//   progressbar: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'progress',
//   },
//   radio: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'input',
//   },
//   scrollbar: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'div',
//   },
//   searchbox: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'input',
//   },
//   singlelinetextbox: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'input',
//   },
//   slider: new SliderDescriptor,
//   spinbutton: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'input',
//   },
//   status: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   switch: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'button',
//   },
//   tab: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'div',
//   },
//   tabpanel: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'div',
//   },
//   timer: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'timer',
//   },
//   tooltip: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'div',
//   },
//   treeitem: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'li',
//   },
//   combobox: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'div',
//   },
//   grid: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'table',
//   },
//   multiselectlistbox: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'select',
//   },
//   singleselectlistbox: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'ul',
//   },
//   menu: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'ul',
//   },
//   menubar: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'ul',
//   },
//   radiogroup: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'div',
//   },
//   tablist: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   tree: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   treegrid: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   article: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   columnheader: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   cell: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   definition: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   directory: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   document: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   feed: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   group: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   heading: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: ['ariaLevel'],
//     tag: (attributes) => `h${attributes.ariaLevel}`,
//   },
//   img: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   unorderedlist: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   orderedlist: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   listitem: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   math: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   note: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   presentation: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   paragraph: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   region: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   row: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'tr',
//   },
//   rowheader: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'th',
//   },
//   separator: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   table: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'table',
//   },
//   tablebody: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'tbody',
//   },
//   tablefoot: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'tfoot',
//   },
//   tablehead: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'thead',
//   },
//   term: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'dt',
//   },
//   toolbar: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'div',
//   },
//   figure: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'figure',
//   },
//   figcaption: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'figcaption',
//   },
//   application: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'div',
//   },
//   banner: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'div',
//   },
//   compementary: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'div',
//   },
//   contentinfo: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   form: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'form',
//   },
//   main: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'main',
//   },
//   navigation: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'nav',
//   },
//   search: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'div',
//   },
//   span: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'span',
//   },
//   format_text_bold: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'b',
//   },
//   format_text_code: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'del',
//   },
//   format_text_delete: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   format_text_emphasize: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'em',
//   },
//   format_text_italic: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'i',
//   },
//   format_text_insert: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'ins',
//   },
//   format_text_kbd: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'kbd',
//   },
//   format_text_preformat: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'pre',
//   },
//   format_text_strikethrough: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 's',
//   },
//   format_text_sample: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'samp',
//   },
//   format_text_small: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'strong',
//   },
//   format_text_strong: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: '',
//   },
//   format_text_subscript: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'sub',
//   },
//   format_text_superscript: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'sup',
//   },
//   format_text_time: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'time',
//   },
//   format_text_underline: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'u',
//   },
//   format_text_variable: {
//     allowedChildren: [],
//     allowedAttributes: [],
//     events: [],
//     requiredAttributes: [],
//     tag: 'var',
//   },
// };

