# This workflow will run tests using node, triggered via push
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Push

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Lint and build CAM
        run: |
          npm ci
          npm run lint
          npm run build
      - name: Lint and build test app
        working-directory: ./test-app
        run: |
          npm ci
          npm run lint
          npm run build
      - name: Test Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
