# This workflow will run tests using node, triggered via push
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Checks

on:
  push:
  workflow_dispatch:
  pull_request_target:
    types: [labeled]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'Safe')
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Lint and build CAM
        run: |
          npm ci
          npm run lint
          npm run build
      - name: Lint and build test app
        working-directory: ./test-app
        run: |
          npm ci
          npm run lint
          npm run build
  coverage:
    needs: build
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          persist-credentials: false
      - name: Test Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
